# Generated by Django 3.2.8 on 2021-11-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(max_length=40),
        ),
    ]
